### ISSUE TITLE
Add inequality chart to population impact

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine#278] opened 2021-12-21 22:26 UTC
Like this, from the Blank Slate report: 
![image](https://user-images.githubusercontent.com/35577657/147005625-2bbd3142-a0f8-4404-97a3-4cb3d644dbfe.png)

**Comment by MaxGhenis** [comment] 2021-12-21 22:43
Duplicate of #180

**Closed by MaxGhenis** 2021-12-21 22:43 UTC
Labels: scoped
