### ISSUE TITLE
AutoUBI throws error and only sets UBI for children

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#517] opened 2022-02-28 18:11 UTC
Repro steps:
1. Set basic rate to 30%
2. Click AutoUBI

Result:
* Error: `Couldn't apply AutoUBI - something went wrong.TypeError: Cannot read properties of undefined (reading 'value')`
* Sets child BI to 13, does not set a adult and pensioner BI

http://policyengine.org/uk/policy?basic_rate=30&child_bi=13

**Comment by nikhilwoodruff** [comment] 2022-03-01 15:07
Caused by an incorrect parameter name (`working_age_bi` -> `adult_bi`). Fixed in #521

**Closed** 2022-03-02 19:56 UTC
Labels: bug, policy, uk
